// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Phone    int32  `json:"phone"`
	Address  string `json:"address"`
}
